# Changes here will be overwritten by Copier
_src_path: /tmp/a017a18b-ac48-4177-a81d-d5b14afa9ad4_step-fetch-base-wTwKtF/template/copier
author_email: man.chan@diamond.ac.uk
author_name: Man Ting Chan
component_owner: user:default/kqd14687
description: test_public
distribution_name: test_public
docker: true
docs_type: README
git_platform: github.com
github_org: kqd14687
package_name: test_public
repo_name: test_public
